routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Select2Controller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('login');
});

Auth::routes();

// Select2 Controller
Route::group(['prefix' => '/select2', 'as' => 'select2.', 'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/select2/select-region', [
        'uses' => 'Select2Controller@selectRegion',
        'as' => 'select-region'
    ]);
    Route::get('/select2/select-mobil-type', [
        'uses' => 'Select2Controller@selectMobilType',
        'as' => 'select-mobil-type'
    ]);
    Route::get('/select2/select-mobil', [
        'uses' => 'Select2Controller@selectMobil',
        'as' => 'select-mobil'
    ]);
    Route::get('/select2/select-driver', [
        'uses' => 'Select2Controller@selectDriver',
        'as' => 'select-driver'
    ]);
});

// Dashboard
Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::group(['prefix' => '/pegawai', 'as' => 'pegawai.', 'namespace' => 'App\Http\Controllers\Pegawai'], function () {
    // List Pegawai
    Route::resource('/pegawai', 'PegawaiController')->except('destroy', 'show');
    Route::get('/pegawai/datatable', [
        'uses' => 'PegawaiController@datatable',
        'as' => 'pegawai.datatable'
    ]);
    Route::post('/pegawai/change-status', [
        'uses' => 'PegawaiController@changeStatus',
        'as' => 'pegawai.change-status'
    ]);
    Route::get('/pegawai/destroy/{id}', [
        'uses' => 'PegawaiController@destroy',
        'as' => 'pegawai.destroy'
    ]);
});

Route::group(['prefix' => '/mobil', 'as' => 'mobil.', 'namespace' => 'App\Http\Controllers\Mobil'], function () {
    // List Mobil
    Route::resource('/mobil', 'MobilController')->except('destroy', 'show');
    Route::get('/mobil/datatable', [
        'uses' => 'MobilController@datatable',
        'as' => 'mobil.datatable'
    ]);
    Route::post('/mobil/change-status', [
        'uses' => 'MobilController@changeStatus',
        'as' => 'mobil.change-status'
    ]);
    Route::get('/mobil/destroy/{id}', [
        'uses' => 'MobilController@destroy',
        'as' => 'mobil.destroy'
    ]);

    // List Mobil
    Route::resource('/mobil-type', 'MobilTypeController')->except('destroy', 'show');
    Route::get('/mobil-type/datatable', [
        'uses' => 'MobilTypeController@datatable',
        'as' => 'mobil-type.datatable'
    ]);
    Route::get('/mobil-type/destroy/{id}', [
        'uses' => 'MobilTypeController@destroy',
        'as' => 'mobil-type.destroy'
    ]);

    // Mobil Log
    Route::get('/mobil-log', [
        'uses' => 'MobilLogController@index',
        'as' => 'mobil-log.index'
    ]);
    Route::get('/mobil-log/datatable', [
        'uses' => 'MobilLogController@datatable',
        'as' => 'mobil-log.datatable'
    ]);

    // Service Log
    Route::resource('/service-log', 'ServiceLogController')->except('destroy', 'show');
    Route::get('/service-log/datatable', [
        'uses' => 'ServiceLogController@datatable',
        'as' => 'service-log.datatable'
    ]);
    Route::put('/service-log/set-laporan/{id}', [
        'uses' => 'ServiceLogController@setLaporan',
        'as' => 'service-log.set-laporan'
    ]);
    Route::post('/service-log/change-status', [
        'uses' => 'ServiceLogController@changeStatus',
        'as' => 'service-log.change-status'
    ]);
    Route::get('/service-log/show/{id}', [
        'uses' => 'ServiceLogController@show',
        'as' => 'service-log.show'
    ]);
    Route::get('/service-log/destroy/{id}', [
        'uses' => 'ServiceLogController@destroy',
        'as' => 'service-log.destroy'
    ]);
});

Route::group(['prefix' => '/region', 'as' => 'region.', 'namespace' => 'App\Http\Controllers\Region'], function () {
    // Region
    Route::resource('/region', 'RegionController')->except('destroy', 'show');
    Route::get('/region/datatable', [
        'uses' => 'RegionController@datatable',
        'as' => 'region.datatable'
    ]);
    Route::get('/region/destroy/{id}', [
        'uses' => 'RegionController@destroy',
        'as' => 'region.destroy'
    ]);
});

Route::group(['prefix' => '/pemesanan', 'as' => 'pemesanan.', 'namespace' => 'App\Http\Controllers\Pemesanan'], function () {
    // Pemesanan Mobil
    Route::resource('/pemesanan-mobil', 'PemesananMobilController')->except('destroy', 'show');
    Route::get('/pemesanan-mobil/datatable', [
        'uses' => 'PemesananMobilController@datatable',
        'as' => 'pemesanan-mobil.datatable'
    ]);
    Route::post('/pemesanan-mobil/change-status', [
        'uses' => 'PemesananMobilController@changeStatus',
        'as' => 'pemesanan-mobil.change-status'
    ]);
    Route::get('/pemesanan-mobil/destroy/{id}', [
        'uses' => 'PemesananMobilController@destroy',
        'as' => 'pemesanan-mobil.destroy'
    ]);
    Route::get('/pemesanan-mobil/export', [
        'uses' => 'PemesananMobilController@export',
        'as' => 'pemesanan-mobil.export'
    ]);
    
});

Route::group(['prefix' => '/riwayat', 'as' => 'riwayat.', 'namespace' => 'App\Http\Controllers\RiwayatPakai'], function () {
    Route::get('/datatable', [
        'uses' => 'RiwayatPakaiController@datatable',
        'as' => 'datatable'
    ]);
    // Route::get('/riwayat-pakai/riwayat/{id}', [
    //     'uses' => 'RiwayatPakaiController@edit',
    //     'as' => 'riwayat-pakai.edit'
    // ]);
});
Route::resource('/riwayat', 'App\Http\Controllers\RiwayatPakai\RiwayatPakaiController')->except('destroy');

resources/views/partials/menu.blade.php
@guest
@else
    <nav class="navbar navbar-expand-md navbar-light bg-dark shadow-sm text-light">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto align-items-md-center d-flex">
                    <li class="nav-item">
                        <a href="{{ route('dashboard') }}" class="nav-link  text-white me-md-2 me-lg-3 @yield('activeMenuDashboard')">
                            Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('pemesanan.pemesanan-mobil.index') }}" class="nav-link text-white me-md-2 me-lg-3 @yield('activeMenuPemesananMobil')">
                            Pemesanan Mobil
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('region.region.index') }}" class="nav-link text-white me-md-2 me-lg-3 @yield('activeMenuRegion')">
                            Region
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="mobilNavDrowpdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true"  aria-expanded="false" v-pre
                        class="nav-link dropdown-toggle text-white me-md-2 me-lg-3 @yield('activeMenuMobil')"">
                            Mobil
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="mobilNavDrowpdown">
                            <li><a class="dropdown-item @yield('activeSubMenuMobiil')" href="{{ route('mobil.mobil.index') }}">List Mobil</a></li>
                            <li><a class="dropdown-item @yield('activeSubMenuMobiilType')" href="{{ route('mobil.mobil-type.index') }}">Tipe Mobil</a></li>
                            <li><a class="dropdown-item @yield('activeSubMenuMobilLog')" href="{{ route('mobil.mobil-log.index') }}">Mobil Log</a></li>
                            <li><a class="dropdown-item @yield('activeSubMenuServiceLog')" href="{{ route('mobil.service-log.index') }}">Service Log</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('pegawai.pegawai.index') }}" class="nav-link text-white me-md-2 me-lg-3 @yield('activeMenuPegawai')">
                            Pegawai
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto ">
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle text-white align-items-center d-flex"
                            href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false" v-pre>
                            <i class="bi bi-person-circle me-2"></i>

                            {{ Auth::user()->employee->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <p class="dropdown-item mb-0">Username : {{ Auth::user()->username }}</p>
                            <p class="dropdown-item mb-0">Level : {{ Auth::user()->isApprover() ? 'Appo' : 'Admin' }}</p>
                            <a class="dropdown-item bg-danger text-white" href="{{ route('logout') }}"
                                onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="bi bi-box-arrow-right me-2"></i>
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
@endguest

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-light  shadow-sm">
    <div class="container">
        <a class="navbar-brand mx-md-auto" href="{{ url('/') }}">
            <img src="{{ asset('img/logo.png') }}" alt="" width="150">
        </a>
        <button class="navbar-toggler ms-auto bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>