routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Select2Controller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('login');
});

Auth::routes();

// Select2 Controller
Route::group(['prefix' => '/select2', 'as' => 'select2.', 'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/select2/select-region', [
        'uses' => 'Select2Controller@selectRegion',
        'as' => 'select-region'
    ]);
    Route::get('/select2/select-mobil-type', [
        'uses' => 'Select2Controller@selectMobilType',
        'as' => 'select-mobil-type'
    ]);
    Route::get('/select2/select-mobil', [
        'uses' => 'Select2Controller@selectMobil',
        'as' => 'select-mobil'
    ]);
    Route::get('/select2/select-driver', [
        'uses' => 'Select2Controller@selectDriver',
        'as' => 'select-driver'
    ]);
});

// Dashboard
Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::group(['prefix' => '/pegawai', 'as' => 'pegawai.', 'namespace' => 'App\Http\Controllers\Pegawai'], function () {
    // List Pegawai
    Route::resource('/pegawai', 'PegawaiController')->except('destroy', 'show');
    Route::get('/pegawai/datatable', [
        'uses' => 'PegawaiController@datatable',
        'as' => 'pegawai.datatable'
    ]);
    Route::post('/pegawai/change-status', [
        'uses' => 'PegawaiController@changeStatus',
        'as' => 'pegawai.change-status'
    ]);
    Route::get('/pegawai/destroy/{id}', [
        'uses' => 'PegawaiController@destroy',
        'as' => 'pegawai.destroy'
    ]);
});

Route::group(['prefix' => '/mobil', 'as' => 'mobil.', 'namespace' => 'App\Http\Controllers\Mobil'], function () {
    // List Mobil
    Route::resource('/mobil', 'MobilController')->except('destroy', 'show');
    Route::get('/mobil/datatable', [
        'uses' => 'MobilController@datatable',
        'as' => 'mobil.datatable'
    ]);
    Route::post('/mobil/change-status', [
        'uses' => 'MobilController@changeStatus',
        'as' => 'mobil.change-status'
    ]);
    Route::get('/mobil/destroy/{id}', [
        'uses' => 'MobilController@destroy',
        'as' => 'mobil.destroy'
    ]);

    // List Mobil
    Route::resource('/mobil-type', 'MobilTypeController')->except('destroy', 'show');
    Route::get('/mobil-type/datatable', [
        'uses' => 'MobilTypeController@datatable',
        'as' => 'mobil-type.datatable'
    ]);
    Route::get('/mobil-type/destroy/{id}', [
        'uses' => 'MobilTypeController@destroy',
        'as' => 'mobil-type.destroy'
    ]);

    // Mobil Log
    Route::get('/mobil-log', [
        'uses' => 'MobilLogController@index',
        'as' => 'mobil-log.index'
    ]);
    Route::get('/mobil-log/datatable', [
        'uses' => 'MobilLogController@datatable',
        'as' => 'mobil-log.datatable'
    ]);

    // Service Log
    Route::resource('/service-log', 'ServiceLogController')->except('destroy', 'show');
    Route::get('/service-log/datatable', [
        'uses' => 'ServiceLogController@datatable',
        'as' => 'service-log.datatable'
    ]);
    Route::put('/service-log/set-laporan/{id}', [
        'uses' => 'ServiceLogController@setLaporan',
        'as' => 'service-log.set-laporan'
    ]);
    Route::post('/service-log/change-status', [
        'uses' => 'ServiceLogController@changeStatus',
        'as' => 'service-log.change-status'
    ]);
    Route::get('/service-log/show/{id}', [
        'uses' => 'ServiceLogController@show',
        'as' => 'service-log.show'
    ]);
    Route::get('/service-log/destroy/{id}', [
        'uses' => 'ServiceLogController@destroy',
        'as' => 'service-log.destroy'
    ]);
});

Route::group(['prefix' => '/region', 'as' => 'region.', 'namespace' => 'App\Http\Controllers\Region'], function () {
    // Region
    Route::resource('/region', 'RegionController')->except('destroy', 'show');
    Route::get('/region/datatable', [
        'uses' => 'RegionController@datatable',
        'as' => 'region.datatable'
    ]);
    Route::get('/region/destroy/{id}', [
        'uses' => 'RegionController@destroy',
        'as' => 'region.destroy'
    ]);
});

Route::group(['prefix' => '/pemesanan', 'as' => 'pemesanan.', 'namespace' => 'App\Http\Controllers\Pemesanan'], function () {
    // Pemesanan Mobil
    Route::resource('/pemesanan-mobil', 'PemesananMobilController')->except('destroy', 'show');
    Route::get('/pemesanan-mobil/datatable', [
        'uses' => 'PemesananMobilController@datatable',
        'as' => 'pemesanan-mobil.datatable'
    ]);
    Route::post('/pemesanan-mobil/change-status', [
        'uses' => 'PemesananMobilController@changeStatus',
        'as' => 'pemesanan-mobil.change-status'
    ]);
    Route::get('/pemesanan-mobil/destroy/{id}', [
        'uses' => 'PemesananMobilController@destroy',
        'as' => 'pemesanan-mobil.destroy'
    ]);
    Route::get('/pemesanan-mobil/export', [
        'uses' => 'PemesananMobilController@export',
        'as' => 'pemesanan-mobil.export'
    ]);
    
});

Route::group(['prefix' => '/riwayat', 'as' => 'riwayat.', 'namespace' => 'App\Http\Controllers\RiwayatPakai'], function () {
    Route::get('/datatable', [
        'uses' => 'RiwayatPakaiController@datatable',
        'as' => 'datatable'
    ]);
    // Route::get('/riwayat-pakai/riwayat/{id}', [
    //     'uses' => 'RiwayatPakaiController@edit',
    //     'as' => 'riwayat-pakai.edit'
    // ]);
});
Route::resource('/riwayat', 'App\Http\Controllers\RiwayatPakai\RiwayatPakaiController')->except('destroy');

app/Models/Region.php
<?php

namespace App\Models;

use App\Traits\CreateByTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    use HasFactory, CreateByTrait;

    public function employee()
    {
        return $this->hasMany(Employee::class, 'id_region', 'id');
    }

    public function vehicle()
    {
        return $this->hasMany(Vehicle::class, 'id_region', 'id');
    }
}

app/Http/Controllers/Region/RegionController.php
<?php

namespace App\Http\Controllers\Region;

use App\Http\Requests\Region\RegionRequest;
use App\Models\Employee;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;
use App\Models\Region;

class RegionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        return view('pages.region.region.index');
    }

    public function datatable(Request $request)
    {
        $data = Region::all();

        return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function ($row) {
                $btn = '
                    <div class="d-flex">
                        <a href="' . route('region.region.edit', $row->id) . '" class="btn-edit btn btn-warning  mx-1 d-flex"><i class="bi bi-pencil-fill me-1"></i>Edit</a>
                        <button onClick="deleteConf(' . $row->id . ')" class="btn btn-danger d-flex  btn-delete">
                            <i class="bi bi-trash-fill me-1"></i>
                            Hapus
                        </button>
                    </div>
                ';

                return $btn;
            })
            ->rawColumns(['action', 'status'])
            ->make(true);
    }

    public function create()
    {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        return view('pages.region.region.create');
    }

    public function store(RegionRequest $request)
    {

        DB::beginTransaction();
        try {
            $dte = new Region();
            $dte->name = $request->name;
            $dte->save();

            activity()->performedOn($dte)->log('Tambah Region');

            DB::commit();
        } catch (\Exception $e) {
            if (env('CATCH_DEBUG'))
                dd($e->getMessage());

            DB::rollBack();
            return redirect()->route('region.region.create')->with('error_msg', "Gagal Menambahkan Region");
        }
        return redirect()->route('region.region.index')->withSuccess('Berhasil Menambahkan Region !');
    }

    public function edit($id)
    {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        $dt = Region::findOrFail($id);
        $data['data'] = $dt;

        return view('pages.region.region.edit', $data);
    }

    public function update(RegionRequest $request, $id)
    {

        DB::beginTransaction();
        try {

            $dte = Region::where('id', $id)->first();
            $dte->name = $request->name;
            $dte->save();

            activity()->performedOn($dte)->log('Update Region');

            DB::commit();
        } catch (\Exception $e) {
            if (env('CATCH_DEBUG'))
                dd($e->getMessage());

            DB::rollBack();
            return redirect()->route('region.region.edit', $dte->id)->with('error_msg', "Gagal Update Region");
        }
        return redirect()->route('region.region.index')->withSuccess('Berhasil Update Region !');
    }

    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            $dt = Region::with('employee', 'vehicle')->findOrFail($id);
            if (empty($dt->employee))
                return redirect()->route('region.region.index')->with('error_msg', 'Region telah mempunyai Pegawai !');
            if (empty($dt->vehicle))
                return redirect()->route('region.region.index')->with('error_msg', 'Region telah mempunyai Mobil');
            
            $dt->delete();
            activity()->performedOn($dt)->log('Update Region');

            DB::commit();
        } catch (\Exception $e) {
            if (env('CATCH_DEBUG'))
                dd($e->getMessage());

            DB::rollBack();
            return redirect()->route('region.region.index')->with('error_msg', "Gagal Hapus Region");
        }
        return redirect()->route('region.region.index')->withSuccess('Berhasil Hapus Region !');
    }
}

resources/views/pages/region/region/create.blade.php
@extends('layouts.app')
@section('title', 'Tambah Region')
@section('activeMenuRegion', 'active')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        <div class="me-auto">
                            Tambah Region
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('region.region.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="col-md-7 offset-md-3 my-4">
                                <h5>Data Region</h5>
                            </div>

                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">Nama Region</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" placeholder="Masukkan Nama Lengkap"
                                        class="form-control @error('name') is-invalid @enderror" name="name"
                                        value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-md-6 offset-md-4 d-flex justify-content-end">
                                    <input type="submit" value="Simpan" class="btn btn-primary pull-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script>
        
    </script>
@endpush

resources/views/pages/region/region/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Region')
@section('activeMenuRegion', 'active')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        <div class="me-auto">
                            Edit Region
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('region.region.update', $data->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="col-md-7 offset-md-3 my-4">
                                <h5>Data Region</h5>
                            </div>

                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">Nama Region</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                        class="form-control @error('name') is-invalid @enderror" name="name"
                                        value="{{ $data->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-md-6 offset-md-4 d-flex justify-content-end">
                                    <input type="submit" value="Update" class="btn btn-info  pull-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script>
        $(document).ready(function() {
            
        })
    </script>
@endpush

resources/views/pages/region/region/index.blade.php
@extends('layouts.app')
@section('title', 'List Region')
@section('activeMenuRegion', 'active')
@section('activeSubMenuPegawai', 'active')

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="w-100 d-flex text-white align-items-center bg-dark p-2">
                            <div class="me-auto ms-2">
                                <h5 class="mb-0">List Region</h5>
                            </div>
                            <div class="ms-auto me-2">
                                <a href="{{ route('region.region.create') }}" class="btn btn-primary"><i
                                        class="bi bi-plus-circle me-2"></i>Tambah Region</a>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-bordered data-table">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th width="100px">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script>
        $(document).ready(function() {
            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                bDestroy: true,
                ajax: "{{ route('region.region.datatable') }}",
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });
        })

        function deleteConf(id) {
            var url = "{{ route('region.region.destroy', ':id') }}"
            url = url.replace(':id', id)

            Swal.fire({
                icon: 'warning',
                title: 'Apa kamu yakin?',
                text: "Anda tidak akan dapat mengembalikan data ini kembali!",
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, hapus!'
            }).then((result) => {
                if (result.value) {
                    window.location.replace(url);
                }
            });
        };
    </script>
@endpush