routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Select2Controller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('login');
});

Auth::routes();

// Select2 Controller
Route::group(['prefix' => '/select2', 'as' => 'select2.', 'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/select2/select-region', [
        'uses' => 'Select2Controller@selectRegion',
        'as' => 'select-region'
    ]);
    Route::get('/select2/select-mobil-type', [
        'uses' => 'Select2Controller@selectMobilType',
        'as' => 'select-mobil-type'
    ]);
    Route::get('/select2/select-mobil', [
        'uses' => 'Select2Controller@selectMobil',
        'as' => 'select-mobil'
    ]);
    Route::get('/select2/select-driver', [
        'uses' => 'Select2Controller@selectDriver',
        'as' => 'select-driver'
    ]);
});

// Dashboard
Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::group(['prefix' => '/pegawai', 'as' => 'pegawai.', 'namespace' => 'App\Http\Controllers\Pegawai'], function () {
    // List Pegawai
    Route::resource('/pegawai', 'PegawaiController')->except('destroy', 'show');
    Route::get('/pegawai/datatable', [
        'uses' => 'PegawaiController@datatable',
        'as' => 'pegawai.datatable'
    ]);
    Route::post('/pegawai/change-status', [
        'uses' => 'PegawaiController@changeStatus',
        'as' => 'pegawai.change-status'
    ]);
    Route::get('/pegawai/destroy/{id}', [
        'uses' => 'PegawaiController@destroy',
        'as' => 'pegawai.destroy'
    ]);
});

Route::group(['prefix' => '/mobil', 'as' => 'mobil.', 'namespace' => 'App\Http\Controllers\Mobil'], function () {
    // List Mobil
    Route::resource('/mobil', 'MobilController')->except('destroy', 'show');
    Route::get('/mobil/datatable', [
        'uses' => 'MobilController@datatable',
        'as' => 'mobil.datatable'
    ]);
    Route::post('/mobil/change-status', [
        'uses' => 'MobilController@changeStatus',
        'as' => 'mobil.change-status'
    ]);
    Route::get('/mobil/destroy/{id}', [
        'uses' => 'MobilController@destroy',
        'as' => 'mobil.destroy'
    ]);

    // List Mobil
    Route::resource('/mobil-type', 'MobilTypeController')->except('destroy', 'show');
    Route::get('/mobil-type/datatable', [
        'uses' => 'MobilTypeController@datatable',
        'as' => 'mobil-type.datatable'
    ]);
    Route::get('/mobil-type/destroy/{id}', [
        'uses' => 'MobilTypeController@destroy',
        'as' => 'mobil-type.destroy'
    ]);

    // Mobil Log
    Route::get('/mobil-log', [
        'uses' => 'MobilLogController@index',
        'as' => 'mobil-log.index'
    ]);
    Route::get('/mobil-log/datatable', [
        'uses' => 'MobilLogController@datatable',
        'as' => 'mobil-log.datatable'
    ]);

    // Service Log
    Route::resource('/service-log', 'ServiceLogController')->except('destroy', 'show');
    Route::get('/service-log/datatable', [
        'uses' => 'ServiceLogController@datatable',
        'as' => 'service-log.datatable'
    ]);
    Route::put('/service-log/set-laporan/{id}', [
        'uses' => 'ServiceLogController@setLaporan',
        'as' => 'service-log.set-laporan'
    ]);
    Route::post('/service-log/change-status', [
        'uses' => 'ServiceLogController@changeStatus',
        'as' => 'service-log.change-status'
    ]);
    Route::get('/service-log/show/{id}', [
        'uses' => 'ServiceLogController@show',
        'as' => 'service-log.show'
    ]);
    Route::get('/service-log/destroy/{id}', [
        'uses' => 'ServiceLogController@destroy',
        'as' => 'service-log.destroy'
    ]);
});

Route::group(['prefix' => '/region', 'as' => 'region.', 'namespace' => 'App\Http\Controllers\Region'], function () {
    // Region
    Route::resource('/region', 'RegionController')->except('destroy', 'show');
    Route::get('/region/datatable', [
        'uses' => 'RegionController@datatable',
        'as' => 'region.datatable'
    ]);
    Route::get('/region/destroy/{id}', [
        'uses' => 'RegionController@destroy',
        'as' => 'region.destroy'
    ]);
});

Route::group(['prefix' => '/pemesanan', 'as' => 'pemesanan.', 'namespace' => 'App\Http\Controllers\Pemesanan'], function () {
    // Pemesanan Mobil
    Route::resource('/pemesanan-mobil', 'PemesananMobilController')->except('destroy', 'show');
    Route::get('/pemesanan-mobil/datatable', [
        'uses' => 'PemesananMobilController@datatable',
        'as' => 'pemesanan-mobil.datatable'
    ]);
    Route::post('/pemesanan-mobil/change-status', [
        'uses' => 'PemesananMobilController@changeStatus',
        'as' => 'pemesanan-mobil.change-status'
    ]);
    Route::get('/pemesanan-mobil/destroy/{id}', [
        'uses' => 'PemesananMobilController@destroy',
        'as' => 'pemesanan-mobil.destroy'
    ]);
    Route::get('/pemesanan-mobil/export', [
        'uses' => 'PemesananMobilController@export',
        'as' => 'pemesanan-mobil.export'
    ]);
    
});

Route::group(['prefix' => '/riwayat', 'as' => 'riwayat.', 'namespace' => 'App\Http\Controllers\RiwayatPakai'], function () {
    Route::get('/datatable', [
        'uses' => 'RiwayatPakaiController@datatable',
        'as' => 'datatable'
    ]);
    // Route::get('/riwayat-pakai/riwayat/{id}', [
    //     'uses' => 'RiwayatPakaiController@edit',
    //     'as' => 'riwayat-pakai.edit'
    // ]);
});
Route::resource('/riwayat', 'App\Http\Controllers\RiwayatPakai\RiwayatPakaiController')->except('destroy');

app/Http/Controllers/Mobil/MobilController.php
<?php

namespace App\Http\Controllers\Mobil;

use App\Http\Requests\Mobil\MobilRequest;
use App\Models\Employee;
use App\Models\Mobil;
use App\Models\Vehicle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;
use App\Models\VehicleType;
use Laravel\Ui\Presets\Vue;

class MobilController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        return view('pages.mobil.mobil.index');
    }


    public function datatable(Request $request)
    {
        $data = Vehicle::with('vehicleType', 'region');

        return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('status', function ($row) {
                $status = Vehicle::STATUS;
                unset($status['maintenance'], $status['in_use']);
                $btn = '';
                if($row->status == 'in_use' || $row->status == 'maintenance') {
                    return Vehicle::STATUS[$row->status];
                } else {
                    $btn .= '<select data-id="' . $row->id . '" class="control-form select-status" >';
                    foreach ($status as $key => $value) {
                        $selected = $row->status == $key ? "selected" : "";
                        $btn .= '<option ' . $selected . ' value="' . $key . '">' . $value . '</option>';
                    }
                    $btn .= '</select>';
                }             

                return $btn;
            })
            ->addColumn('action', function ($row) {
                $btn = '
                    <div class="d-flex">
                        <a href="' . route('mobil.mobil.edit', $row->id) . '" class="btn-edit btn btn-warning mx-1 d-flex"><i class="bi bi-pencil-fill me-1"></i>Edit</a>
                        <button onClick="deleteConf(' . $row->id . ')" class="btn btn-danger d-flex btn-delete">
                            <i class="bi bi-trash-fill me-1"></i>
                            Hapus
                        </button>
                    </div>
                ';

                return $btn;
            })
            ->rawColumns(['action', 'status'])
            ->make(true);
    }

    public function changeStatus(MobilRequest $request)
    {
        DB::beginTransaction();
        try {
            $dt = Vehicle::where('id', $request->id)->first();
            if ($dt->status == 'in_use') {
                return response()->json([
                    'success' => false,
                    'message' => "Tidak bisa mengganti status ketika mobil sedang digunakan !",
                    'data' => 'Mohon maaf !'
                ], 422);
            }
            if ($request->status == 'in_use') {
                return response()->json([
                    'success' => false,
                    'message' => "Tidak bisa mengganti status ke Dipakai tanpa booking terlebih dahulu !",
                    'data' => 'Mohon maaf !'
                ], 422);
            }
            $dt->status = $request->status;
            $dt->save();

            DB::commit();
        } catch (\Exception $e) {
            if (env('CATCH_DEBUG'))
                dd($e->getMessage());

            DB::rollBack();
            return response()->json([
                'success' => false,
                'message' => "Gagal Merubah Status Mobil !",
                'data' => 'Terjadi Kesalahan !'
            ], 500);
        }

        return response()->json([
            'success' => true,
            'message' => 'Berhasil mengubah Status Mobil !',
        ]);
    }

    public function create() {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        $data['ownership'] = Vehicle::OWNERSHIP;

        return view('pages.mobil.mobil.create', $data);
    }

    public function store(MobilRequest $request) {

        DB::beginTransaction();
        try {
            $dte = new Vehicle();
            $dte->id_type = $request->id_type;
            $dte->id_region = $request->id_region;
            $dte->name = $request->name;
            $dte->ownership = $request->ownership;
            $dte->license_plate = $request->license_plate;
            $dte->status = 'available';
            $dte->save();
            
            DB::commit();
        } catch (\Exception $e) {
            if (env('CATCH_DEBUG'))
                dd($e->getMessage());

            DB::rollBack();
            return redirect()->route('mobil.mobil.create')->with('error_msg', "Gagal Menambahkan Mobil");

        }
        return redirect()->route('mobil.mobil.index')->withSuccess('Berhasil Menambahkan Mobil !');
    }

    public function edit($id) {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        $dt = Vehicle::with('vehicleType', 'region')->findOrFail($id);
        $data['data'] = $dt;
        $data['ownership'] = Vehicle::OWNERSHIP;

        return view('pages.mobil.mobil.edit', $data);
    }

    public function update(MobilRequest $request, $id) {

        DB::beginTransaction();
        try {
            $dte = Vehicle::find($id);
            $dte->id_type = $request->id_type;
            $dte->id_region = $request->id_region;
            $dte->name = $request->name;
            $dte->ownership = $request->ownership;
            $dte->license_plate = $request->license_plate;
            $dte->status = 'available';
            $dte->save();

            DB::commit();
        } catch (\Exception $e) {
            if (env('CATCH_DEBUG'))
                dd($e->getMessage());

            DB::rollBack();
            return redirect()->route('mobil.mobil.edit', $dte->id)->with('error_msg', "Gagal Update Mobil");

        }
        return redirect()->route('mobil.mobil.index')->withSuccess('Berhasil Update Mobil !');
    }

    public function destroy($id) {
        DB::beginTransaction();
        try {
            $dt = Vehicle::findOrFail($id);
            $dt->delete();

            DB::commit();
        } catch (\Exception $e) {
            if (env('CATCH_DEBUG'))
                dd($e->getMessage());

            DB::rollBack();
            return redirect()->route('mobil.mobil.index')->with('error_msg', "Gagal Hapus Mobil");

        }
        return redirect()->route('mobil.mobil.index')->withSuccess('Berhasil Hapus Mobil !');
    }
}

app/Http/Controllers/Mobil/MobilLogController.php
<?php

namespace App\Http\Controllers\Mobil;

use App\Http\Requests\UserRequest;
use App\Models\Employee;
use App\Models\User;
use App\Models\Vehicle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;

class MobilLogController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        return view('pages.mobil.mobil-log.index');
    }


    public function datatable(Request $request)
    {
        $data = Vehicle::with('vehicleType', 'region');

        if (!empty($request->mobil))
            $data = $data->where('id', $request->mobil);
        if (!empty($request->mobilType))
            $data = $data->where('id_type', $request->mobilType);
        if (!empty($request->ownership))
            $data = $data->where('ownership', $request->ownership);

        return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('status', function ($row) {
                $btn = '';
                $checked = true;
                if (empty($row->status))
                    $checked = false;

                $btn .= '
                            <button onClick="updateStatus(' . $row->id . ')" class="btn btn-info d-flex text-white">
                                <i class="bi bi-info-circle me-2"></i>
                                <span class="text-capitalize ">Status : <b>' . $row->status . '</b></span>
                            </button>
                        ';

                return $btn;
            })
            ->addColumn('action', function ($row) {
                $btn = '
                            <div class="d-flex">
                                <a href="' . route('riwayat.show', $row->id) . '" class="btn-edit btn btn-warning mx-1 d-flex"><i class="bi bi-eye-fill me-1"></i>Riwayat Pemakaian</a>
                            </div>
                        ';

                return $btn;
            })
            ->rawColumns(['action', 'status'])
            ->make(true);
    }
}

resources/views/pages/mobil/mobil-log/index.blade.php
@extends('layouts.app')
@section('title', 'Daftar Mobil')
@section('activeMenuMobil', 'active')
@section('activeSubMenuMobilLog', 'active')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-light d-flex justify-content-start align-items-center text-white">
                        <ul class="nav nav-pills nav-fill">
                            <li class="nav-item">
                                <a class="nav-link @yield('activeSubMenuMobil')" aria-current="page" href="{{ route('mobil.mobil.index') }}">List Mobil Type</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link @yield('activeSubMenuMobilType')" href="{{ route('mobil.mobil-type.index') }}">Mobil Type</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link @yield('activeSubMenuMobilLog')" href="{{ route('mobil.mobil-log.index') }}">Riwayat Pemakaian Mobil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link @yield('activeSubMenuServiceLog')" href="{{ route('mobil.service-log.index') }}">Service Log</a>
                            </li>
                        </ul>
                    </div>

                    <div class="card-body">
                        <div class="w-100 d-flex text-white align-items-center bg-dark p-2">
                            <div class="me-auto ms-2">
                                <h5 class="mb-0">List Mobil</h5>
                            </div>
                        </div>

                        <div class="row my-4">
                            <h5 class="mb-2">Filter Table</h5>
                            <div class="form-group col-md-3 col-sm-12">
                                <label>Type Mobil</label>
                                <select name="id_type" class="form-control" id="selectMobilType" autofocus>

                                </select>
                            </div>
                            <div class="form-group col-md-3 col-sm-12">
                                <label>Ownership</label>
                                <select name="id_mobil" class="form-control" id="selectOwnership" autofocus>
                                    <option value="" selected disabled>Pilih Ownership</option>
                                    <option value="owned">Owned</option>
                                    <option value="leased">Leased</option>
                                </select>
                            </div>
                            <div class="form-group col-md-3 col-sm-12">
                                <label>Mobil</label>
                                <select name="id_mobil" class="form-control" id="selectMobil" autofocus>

                                </select>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-bordered data-table">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Tipe Mobil</th>
                                        <th>Kepemilikan</th>
                                        <th>Plat Nomor</th>
                                        <th>Region</th>
                                        <th>Status</th>
                                        <th width="100px">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script>
        $(document).ready(function() {
            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                bDestroy: true,
                ajax: {
                    tupe: "GET",
                    url: "{{ route('mobil.mobil-log.datatable') }}",
                    data: function(d) {
                        d.mobilType = $('#selectMobilType').val();
                        d.ownership = $('#selectOwnership').val();
                        d.mobil = $('#selectMobil').val();
                    },
                },
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'vehicle_type.type_name',
                        name: 'vehicleType.type_name'
                    },
                    {
                        data: 'license_plate',
                        name: 'license_plate'
                    },
                    {
                        data: 'ownership',
                        name: 'ownership'
                    },
                    {
                        data: 'region.name',
                        name: 'region.name'
                    },
                    {
                        data: 'status',
                        name: 'status',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });

            $('#selectMobilType').select2({
                placeholder: 'Pilih Mobil Type',
                theme: 'bootstrap-5',
                width: '100%',
                allowClear: true,
                ajax: {
                    url: "{{ route('select2.select-mobil-type') }}",
                    dataType: 'json',
                    delay: 250,
                    data: function(params) {
                        return {
                            term: params.term || '',
                            page: params.page || 1,
                        }
                    },
                    cache: true
                }
            }).on('select2:select', (e) => {
                table.draw();
            });

            $('#selectOwnership').select2({
                theme: 'bootstrap-5',
                placeholder: 'Pilih Ownership',
                allowClear: true,
            }).on('select2:select', (e) => {
                table.draw();
            });

            $('#selectMobil').select2({
                placeholder: 'Pilih Region',
                theme: 'bootstrap-5',
                width: '100%',
                allowClear: true,
                ajax: {
                    url: "{{ route('select2.select-mobil') }}",
                    dataType: 'json',
                    delay: 250,
                    data: function(params) {
                        return {
                            term: params.term || '',
                            page: params.page || 1,
                            type: $('#selectMobilType').val(),
                        }
                    },
                    cache: true
                }
            }).on('select2:select', (e) => {
                table.draw();
            });

            $(document).on('change', '.select-status', function(e) {
                e.preventDefault();

                let id = $(this).data('id');
                let status = $(this).val();
                let token = $("meta[name='csrf-token']").attr("content");;

                $.ajax({
                    url: "{{ route('mobil.service-log.change-status') }}",
                    method: 'POST',
                    data: {
                        id: id,
                        "_token": token,
                        status: status
                    },
                    beforeSend: function() {
                        swal.fire({
                            title: 'Sedang mengirim ke server, mohon tunggu...',
                            allowEscapeKey: false,
                            allowOutsideClick: false,
                            didOpen: () => {
                                swal.showLoading();
                            }
                        })
                    },
                    success: function(response) {
                        Swal.fire({
                            title: "Berhasil",
                            text: response.message,
                            icon: "success"
                        });
                        table.draw();
                    },
                    error: function(err) {
                        if (err.status == 422) {
                            txtErr = JSON.parse(err.responseText);
                            swal.fire('Gagal', txtErr.message, 'error')
                        } else {
                            swal.fire('Gagal', err.statusText, 'error')
                        }
                        table.draw();
                    },
                });
            })
        })

    </script>
@endpush